version: "3.9"

networks:
  elastic:
    external: false
    name: elastic

services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch01
    environment:
      # - discovery.type=single-node
      - discovery.seed_hosts=elasticsearch01
      - cluster.name=elastic-cluster
      - node.name=elasticsearch01
      - cluster.initial_master_nodes=elasticsearch01
    restart: always
    networks:
      - elastic
    volumes:
      - $PWD/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch01:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch01
